[server]
address = "0.0.0.0"
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00a3e0"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[runner]
fastReruns = true
